package com.avalon.cwm.backend.server

internal const val LOGIN_PAGE_HTML = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<title>访问验证 · 刺猬猫下载器</title>
<script>
(function(){try{var t=localStorage.getItem('theme');if(!t)t=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';document.documentElement.dataset.theme=t}catch(e){}})();
</script>
<style>
*{margin:0;padding:0;box-sizing:border-box}html,body{width:100%;min-height:100%}
body{height:100vh;min-height:100svh;display:flex;justify-content:center;align-items:center;position:relative;overflow:hidden;padding:24px;font-family:-apple-system,"PingFang SC","Segoe UI",Roboto,sans-serif;background:linear-gradient(to top left,#f5f7f9,#e9edf1,#dfe5ea);color:#596574}
html[data-theme="dark"] body{background:linear-gradient(to top left,#232427,#1d1e21,#18191c);color:#e6e8ed}
.container{width:min(100%,420px);position:relative;z-index:2;isolation:isolate;overflow:hidden;padding:clamp(24px,5vi,34px);text-align:center;color:inherit;border:1px solid rgba(255,255,255,.88);border-radius:26px;background:rgba(255,255,255,.56);-webkit-backdrop-filter:blur(16px) saturate(1.25);backdrop-filter:blur(16px) saturate(1.25);box-shadow:0 18px 50px rgba(73,86,101,.16),inset 0 1px 0 rgba(255,255,255,.82)}
html[data-theme="dark"] .container{background:rgba(255,255,255,.075);border-color:rgba(255,255,255,.13);box-shadow:0 18px 50px rgba(0,0,0,.28),inset 0 1px 0 rgba(255,255,255,.12)}
.container::before{content:'';position:absolute;inset:0;z-index:-1;pointer-events:none;background:radial-gradient(75% 60% at 0 0,rgba(168,216,234,.22),transparent 68%),radial-gradient(70% 58% at 100% 100%,rgba(201,182,228,.16),transparent 70%)}
.container h1{font-size:clamp(30px,8vw,40px);font-weight:300;letter-spacing:2px;margin-bottom:10px;color:#465361;transition:transform 1s ease-in-out,opacity .5s ease-in-out}html[data-theme="dark"] .container h1{color:#e6e8ed}
.sub{margin-bottom:15px;color:#77838f;font-size:14px;line-height:1.6;transition:opacity .35s ease}html[data-theme="dark"] .sub{color:#a7adb8}
.form{display:flex;flex-direction:column;align-items:center;position:relative;z-index:2;opacity:1;transition:opacity .5s ease,transform .5s cubic-bezier(.23,1,.32,1)}
.form input{width:250px;min-height:48px;outline:none;border:1px solid rgba(102,114,126,.22);background:rgba(255,255,255,.48);border-radius:16px;margin:0 auto 10px;padding:10px 15px;text-align:center;color:#4d5c6b;font-size:15px;transition:background-color .25s ease,width .25s ease,border-color .25s ease}
html[data-theme="dark"] .form input{background:rgba(255,255,255,.07);border-color:rgba(255,255,255,.12);color:#e6e8ed}.form input::placeholder{color:#7e8994;font-size:14px;font-weight:300}.form input:hover{background:rgba(255,255,255,.68)}html[data-theme="dark"] .form input:hover{background:rgba(255,255,255,.1)}.form input:focus{width:300px;background:#fff;color:#4d5c6b;border-color:#9aa7b3}html[data-theme="dark"] .form input:focus{background:#2a2c31;color:#eef0f4}
.btn-login{position:relative;width:250px;min-height:48px;overflow:hidden;isolation:isolate;outline:none;appearance:none;-webkit-appearance:none;-webkit-tap-highlight-color:transparent;-webkit-focus-ring-color:transparent;touch-action:manipulation;user-select:none;-webkit-user-select:none;background:#fff;color:#596574;border:1px solid rgba(102,114,126,.1);border-radius:16px;padding:10px 15px;font-size:15px;font-weight:600;cursor:pointer;transform:translateY(0) scale(1);box-shadow:0 6px 16px rgba(73,86,101,.08),inset 0 1px 0 rgba(255,255,255,.82);transition:background-color .2s ease,transform .24s cubic-bezier(.23,1,.32,1),box-shadow .24s cubic-bezier(.23,1,.32,1),opacity .2s ease}html[data-theme="dark"] .btn-login{background:#596574;color:#fff;border-color:transparent;box-shadow:0 6px 18px rgba(0,0,0,.18),inset 0 1px 0 rgba(255,255,255,.1)}.btn-login:active,.btn-login.is-pressed{transform:translateY(1px) scale(.965);box-shadow:0 2px 7px rgba(73,86,101,.1),inset 0 3px 8px rgba(73,86,101,.16);transition:transform .1s cubic-bezier(.23,1,.32,1),box-shadow .1s ease}html[data-theme="dark"] .btn-login:active,html[data-theme="dark"] .btn-login.is-pressed{box-shadow:0 2px 7px rgba(0,0,0,.18),inset 0 3px 9px rgba(0,0,0,.22)}.btn-login:focus-visible{box-shadow:0 0 0 3px rgba(89,101,116,.18),0 6px 16px rgba(73,86,101,.08),inset 0 1px 0 rgba(255,255,255,.82)}html[data-theme="dark"] .btn-login:focus-visible{box-shadow:0 0 0 3px rgba(255,255,255,.2),0 6px 18px rgba(0,0,0,.18),inset 0 1px 0 rgba(255,255,255,.1)}.btn-login:disabled{opacity:.72;cursor:wait}.btn-label{position:relative;z-index:2;display:inline-block;transition:transform .1s cubic-bezier(.23,1,.32,1),opacity .2s ease}.btn-login.is-pressed .btn-label{transform:translateY(1px)}.btn-ripple{position:absolute;z-index:1;left:50%;top:50%;width:1px;height:1px;border-radius:50%;pointer-events:none;background:radial-gradient(circle,rgba(89,101,116,.38) 0,rgba(89,101,116,.24) 36%,rgba(89,101,116,.1) 60%,rgba(89,101,116,0) 76%);transform:translate(-50%,-50%) scale(.08);opacity:0}.btn-ripple.show{animation:login-ripple .56s cubic-bezier(.23,1,.32,1) forwards}html[data-theme="dark"] .btn-ripple{background:radial-gradient(circle,rgba(255,255,255,.44) 0,rgba(255,255,255,.26) 36%,rgba(255,255,255,.1) 60%,rgba(255,255,255,0) 76%)}@keyframes login-ripple{0%{transform:translate(-50%,-50%) scale(.08);opacity:.76}58%{opacity:.42}100%{transform:translate(-50%,-50%) scale(1);opacity:0}}.err{width:250px;min-height:19px;margin:10px auto 0;color:#c65763;font-size:13px;line-height:1.5;text-align:center}
.container.success h1{transform:translateY(75px);opacity:.78}.container.success .sub{opacity:0}.container.success .form{opacity:0;visibility:hidden;transform:translateY(10px)}
.bg-squares{list-style:none;position:fixed;inset:0;z-index:1;overflow:hidden;pointer-events:none}.bg-squares li{position:absolute;bottom:-160px;width:40px;height:40px;background:rgba(126,136,148,.12);animation:square 20s linear infinite}html[data-theme="dark"] .bg-squares li{background:rgba(210,220,232,.08)}
.bg-squares li:nth-child(1){left:10%}.bg-squares li:nth-child(2){left:20%;width:80px;height:80px;animation-delay:2s;animation-duration:17s}.bg-squares li:nth-child(3){left:25%;animation-delay:4s}.bg-squares li:nth-child(4){left:40%;width:60px;height:60px;animation-duration:22s}.bg-squares li:nth-child(5){left:70%}.bg-squares li:nth-child(6){left:80%;width:120px;height:120px;animation-delay:3s}.bg-squares li:nth-child(7){left:32%;width:150px;height:150px;animation-delay:7s}.bg-squares li:nth-child(8){left:55%;width:20px;height:20px;animation-delay:15s;animation-duration:40s}.bg-squares li:nth-child(9){left:25%;width:10px;height:10px;animation-delay:2s;animation-duration:40s}.bg-squares li:nth-child(10){left:90%;width:150px;height:150px;animation-delay:11s}@keyframes square{0%{transform:translateY(0)}100%{transform:translateY(-120vh) rotate(600deg)}}
#handoff{position:fixed;inset:0;z-index:20;pointer-events:none;opacity:0;background:#f2f3f5;transition:opacity .22s cubic-bezier(.23,1,.32,1)}html[data-theme="dark"] #handoff{background:#1c1c1e}#handoff.show{opacity:1}
@media(max-width:420px){body{padding:18px}.container{padding:24px 20px}.form input,.btn-login,.err{width:min(250px,100%)}.form input:focus{width:min(300px,100%)}}
@media(prefers-reduced-motion:reduce){.bg-squares{display:none}.container h1,.form,.sub,.form input,.btn-login,.btn-label,#handoff{transition:none}.btn-login:active,.btn-login.is-pressed{transform:none}.btn-login.is-pressed .btn-label{transform:none}.btn-ripple.show{animation:login-ripple-fade .22s ease-out forwards}.container.success h1{transform:none}}@keyframes login-ripple-fade{from{opacity:.46}to{opacity:0}}
</style></head><body>
<div class="container" id="container"><h1>访问验证</h1><div class="sub">请输入访问密码以继续</div><form class="form" id="login-form"><input type="password" id="pw" placeholder="访问密码" autocomplete="current-password"><button class="btn-login" id="btn" type="submit"><span class="btn-label">进入</span><span class="btn-ripple" aria-hidden="true"></span></button><div class="err" id="err" aria-live="polite"></div></form></div>
<ul class="bg-squares" aria-hidden="true"><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li></ul><div id="handoff"></div>
<script>
const container=document.getElementById('container'),form=document.getElementById('login-form'),pw=document.getElementById('pw'),btn=document.getElementById('btn'),err=document.getElementById('err'),handoff=document.getElementById('handoff'),btnLabel=btn.querySelector('.btn-label'),ripple=btn.querySelector('.btn-ripple');let busy=false;function triggerRipple(event){if(busy)return;const rect=btn.getBoundingClientRect(),point=event.touches&&event.touches[0]?event.touches[0]:event,x=typeof point.clientX==='number'?point.clientX-rect.left:rect.width/2,y=typeof point.clientY==='number'?point.clientY-rect.top:rect.height/2,px=Math.max(0,Math.min(rect.width,x)),py=Math.max(0,Math.min(rect.height,y)),maxX=Math.max(px,rect.width-px),maxY=Math.max(py,rect.height-py),size=2*Math.sqrt(maxX*maxX+maxY*maxY);ripple.style.left=px+'px';ripple.style.top=py+'px';ripple.style.width=size+'px';ripple.style.height=size+'px';ripple.classList.remove('show');void ripple.offsetWidth;ripple.classList.add('show')}function pressButton(event){if(busy)return;btn.classList.add('is-pressed');triggerRipple(event)}function releaseButton(){btn.classList.remove('is-pressed')}if(window.PointerEvent){btn.addEventListener('pointerdown',pressButton);btn.addEventListener('pointerup',releaseButton);btn.addEventListener('pointercancel',releaseButton);btn.addEventListener('pointerleave',releaseButton)}else{btn.addEventListener('touchstart',pressButton,false);btn.addEventListener('touchend',releaseButton,false);btn.addEventListener('touchcancel',releaseButton,false);btn.addEventListener('mousedown',pressButton,false);window.addEventListener('mouseup',releaseButton,false)}btn.addEventListener('keydown',function(event){if((event.key==='Enter'||event.key===' ')&&!event.repeat)pressButton(event)});btn.addEventListener('keyup',releaseButton);btn.addEventListener('blur',releaseButton);ripple.addEventListener('animationend',function(){ripple.classList.remove('show')});
async function go(){if(busy)return;err.textContent='';if(!pw.value){err.textContent='请输入访问密码';pw.focus();return}busy=true;btn.disabled=true;btnLabel.textContent='验证中…';try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:pw.value})});if(r.ok){container.classList.add('success');btnLabel.textContent='进入中…';await new Promise(x=>setTimeout(x,360));handoff.classList.add('show');await new Promise(x=>setTimeout(x,320));location.href='/';return}const d=await r.json().catch(()=>({}));err.textContent=d.error||'密码错误';pw.value='';pw.focus()}catch(e){err.textContent='连接失败，请稍后重试'}busy=false;btn.disabled=false;btnLabel.textContent='进入'}
form.addEventListener('submit',e=>{e.preventDefault();go()});pw.focus();
</script></body></html>
"""
